"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const updateMainInfoController_1 = require("../controllers/updateMainInfoController");
const checkTokenController_1 = require("../controllers/checkTokenController");
const updateDayController_1 = require("../controllers/updateDayController");
const createDayController_1 = require("../controllers/createDayController");
const modifyIncludedExcursionsTripController_1 = require("../controllers/modifyIncludedExcursionsTripController");
const modifyServicesTripController_1 = require("../controllers/modifyServicesTripController");
const modifyOptionalExcursionsTripController_1 = require("../controllers/modifyOptionalExcursionsTripController");
const modifyContactTripController_1 = require("../controllers/modifyContactTripController");
const uploadMiddleware_1 = require("../middleware/uploadMiddleware");
const updatePhotoTripController_1 = require("../controllers/updatePhotoTripController");
const deleteTripController_1 = require("../controllers/deleteTripController");
const addTripController_1 = require("../controllers/addTripController");
const dashboardRouter = (0, express_1.Router)();
dashboardRouter.get("/", checkTokenController_1.checkToken);
dashboardRouter.patch("/updateMainInfo", updateMainInfoController_1.patchMainInfo);
dashboardRouter.patch("/updateDay", updateDayController_1.patchDay);
dashboardRouter.post("/createDay", createDayController_1.createDay);
dashboardRouter.post("/modifyIncludedExcursionsTrip", modifyIncludedExcursionsTripController_1.modifyIncludedExcursionsTrip);
dashboardRouter.post("/modifyServicesTrip", modifyServicesTripController_1.modifyServicesTrip);
dashboardRouter.post("/modifyOptionalExcursionsTrip", modifyOptionalExcursionsTripController_1.modifyOptionalExcursionsTrip);
dashboardRouter.post("/modifyContactTrip", modifyContactTripController_1.modifyContactTrip);
dashboardRouter.post("/updatePhotoTrip", uploadMiddleware_1.upload.single("photo"), updatePhotoTripController_1.updatePhotoTripController);
dashboardRouter.delete("/deleteTrip", deleteTripController_1.deleteTripController);
dashboardRouter.post("/addTrip", addTripController_1.addTripController);
exports.default = dashboardRouter;
